import { FastifyReply, FastifyRequest } from 'fastify';
import jwt from 'jsonwebtoken';
import { RoleType } from '@prisma/client';
import { env } from '../config/env.js';
import { AuthenticatedUserPayload } from '../common/types.js';
import { errorResponse } from '../common/response.js';
import { prisma } from '../lib/prisma.js';

export async function authenticate(req: FastifyRequest, reply: FastifyReply) {
  let token: string | undefined;

  // Check Authorization header
  const authHeader = req.headers.authorization;
  if (authHeader && authHeader.startsWith('Bearer ')) {
    token = authHeader.substring(7);
  } else if (req.cookies && req.cookies.access_token) {
    token = req.cookies.access_token;
  }

  if (!token) {
    return reply.status(401).send(errorResponse('Authentication required', 'UNAUTHORIZED'));
  }

  // Support demo / dev tokens generated by RoleQuickSwitcher and frontend role selection
  if (token.startsWith('demo-token-') || token.startsWith('demo-jwt-token-')) {
    let targetRole = token.replace('demo-token-', '').replace('demo-jwt-token-', '');
    if (targetRole === 'BOOTH_INCHARGE') targetRole = 'BOOTH_PRESIDENT';
    if (targetRole === 'VIEWER') targetRole = 'CONSTITUENCY_INCHARGE';
    const roleEnum = Object.values(RoleType).find((r) => r === targetRole);

    const canonicalCodeMap: Record<string, string> = {
      CONSTITUENCY_INCHARGE: 'MLA-KDP-01',
      MANDAL_INCHARGE: 'MNDL-KDP-01',
      VILLAGE_INCHARGE: 'VILL-KDP-01',
      BOOTH_PRESIDENT: 'BTH-101-01',
      POLLING_AGENT: 'BTH-101-01',
      VOTER_100_INCHARGE: 'INC-100-B145A',
      PARLIAMENT_INCHARGE: 'STATE-APEX-01',
      ZONE_INCHARGE: 'SUPER-ADMIN-01',
      STATE_ADMIN: 'TPCC-2346-5109',
      SUPER_ADMIN: 'TPCC-2345-5101',
    };

    const targetUserCode = roleEnum ? canonicalCodeMap[roleEnum] : undefined;

    const user = await prisma.user.findFirst({
      where: {
        accountStatus: 'ACTIVE',
        ...(targetUserCode ? { userCode: targetUserCode } : (roleEnum ? { role: roleEnum } : {})),
      },
      select: {
        id: true,
        userCode: true,
        mobileNumber: true,
        role: true,
        accountStatus: true,
        organisationId: true,
        unitId: true,
      },
    });

    if (user) {
      req.user = {
        userId: user.id,
        userCode: user.userCode,
        mobileNumber: user.mobileNumber,
        role: user.role,
        organisationId: user.organisationId,
        unitId: user.unitId,
      };
      return;
    }
  }

  try {
    const decoded = jwt.verify(token, env.JWT_SECRET) as AuthenticatedUserPayload;
    
    // Ensure user is still active in database
    const user = await prisma.user.findUnique({
      where: { id: decoded.userId },
      select: {
        id: true,
        userCode: true,
        mobileNumber: true,
        role: true,
        accountStatus: true,
        organisationId: true,
        unitId: true,
      },
    });

    if (!user || user.accountStatus !== 'ACTIVE') {
      return reply.status(401).send(errorResponse('Account is inactive or suspended', 'ACCOUNT_INACTIVE'));
    }

    req.user = {
      userId: user.id,
      userCode: user.userCode,
      mobileNumber: user.mobileNumber,
      role: user.role,
      organisationId: user.organisationId,
      unitId: user.unitId,
    };
  } catch (err) {
    return reply.status(401).send(errorResponse('Invalid or expired authentication token', 'INVALID_TOKEN'));
  }
}

export async function optionalAuthenticate(req: FastifyRequest) {
  const authHeader = req.headers.authorization;
  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    return;
  }

  const token = authHeader.substring(7);
  if (token.startsWith('demo-token-') || token.startsWith('demo-jwt-token-')) {
    let targetRole = token.replace('demo-token-', '').replace('demo-jwt-token-', '');
    if (targetRole === 'BOOTH_INCHARGE') targetRole = 'BOOTH_PRESIDENT';
    if (targetRole === 'VIEWER') targetRole = 'CONSTITUENCY_INCHARGE';
    const roleEnum = Object.values(RoleType).find((r) => r === targetRole);

    const canonicalCodeMap: Record<string, string> = {
      CONSTITUENCY_INCHARGE: 'MLA-KDP-01',
      MANDAL_INCHARGE: 'MNDL-KDP-01',
      VILLAGE_INCHARGE: 'VILL-KDP-01',
      BOOTH_PRESIDENT: 'BTH-101-01',
      POLLING_AGENT: 'BTH-101-01',
      VOTER_100_INCHARGE: 'INC-100-B145A',
      PARLIAMENT_INCHARGE: 'STATE-APEX-01',
      ZONE_INCHARGE: 'SUPER-ADMIN-01',
      STATE_ADMIN: 'TPCC-2346-5109',
      SUPER_ADMIN: 'TPCC-2345-5101',
    };

    const targetUserCode = roleEnum ? canonicalCodeMap[roleEnum] : undefined;

    const user = await prisma.user.findFirst({
      where: {
        accountStatus: 'ACTIVE',
        ...(targetUserCode ? { userCode: targetUserCode } : (roleEnum ? { role: roleEnum } : {})),
      },
      select: {
        id: true,
        userCode: true,
        mobileNumber: true,
        role: true,
        accountStatus: true,
        organisationId: true,
        unitId: true,
      },
    });

    if (user) {
      req.user = {
        userId: user.id,
        userCode: user.userCode,
        mobileNumber: user.mobileNumber,
        role: user.role,
        organisationId: user.organisationId,
        unitId: user.unitId,
      };
      return;
    }
  }

  try {
    const decoded = jwt.verify(token, env.JWT_SECRET) as AuthenticatedUserPayload;
    req.user = decoded;
  } catch {
    // Ignore invalid token in optional mode
  }
}

export function generateToken(payload: AuthenticatedUserPayload): string {
  return jwt.sign(payload, env.JWT_SECRET, { expiresIn: '7d' });
}

